### ISSUE TITLE
This is outdated

### ISSUE THREAD

**Issue by monnier** [sml-nj/sml-mode#1]
The latest sml-mode is at https://elpa.gnu.org/packages/sml-mode.html (this has been the case for almost 9 years now).

**Comment by k4rtik** [comment]
This is great to know, thanks!

Also, it looks like the latest sml-mode already is on git: https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=shortlog;h=refs/heads/externals/sml-mode

I am archiving this repo.
